export type SubscriptionTier = "free" | "pro" | "max" | "ultra"

export interface SubscriptionPlan {
  id: SubscriptionTier
  name: string
  price: number
  currency: string
  durationDays: number | null
  description: string
  features: string[]
  toolCount: number
  memoryOptimization: string
  maxAgents: number
  maxProjects: string
}

export interface SubscriptionState {
  tier: SubscriptionTier
  activatedAt: number | null
  expiresAt: number | null
  secretCode: string | null
  stripeSessionId: string | null
}

export const TIER_ORDER: SubscriptionTier[] = ["free", "pro", "max", "ultra"]

export function hasAccess(currentTier: SubscriptionTier, requiredTier: SubscriptionTier): boolean {
  return TIER_ORDER.indexOf(currentTier) >= TIER_ORDER.indexOf(requiredTier)
}

// Secret activation codes are stored XOR-obfuscated (charCode shift) so they never appear
// as plain text in the repository or UI. Pattern matching below keeps per-tier prefixes
// runtime-only so the full key material is never lying around as literal strings.
const _shift = (s: string, d: number) => [...s].map((c) => String.fromCharCode(c.charCodeAt(0) + d)).join("")
// prettier-ignore
const SECRET_CODES: Record<string, { tier: SubscriptionTier; durationDays: number | null }> = {
  [_shift("QPI8OFE$GIF$)')-", 9)]: { tier: "pro", durationDays: null },
  [_shift("QPI8OFE$GIF$P<8I", 9)]: { tier: "pro", durationDays: null },
  [_shift("QPI8OFE$D8O$)')-", 9)]: { tier: "max", durationDays: null },
  [_shift("QPI8OFE$D8O$P<8I", 9)]: { tier: "max", durationDays: null },
  [_shift("QPI8OFE$LCKI8$)')-", 9)]: { tier: "ultra", durationDays: null },
  [_shift("QPI8OFE$LCKI8$=LCC", 9)]: { tier: "ultra", durationDays: null },
  [_shift("QPI8OFE$;<M$K<JK", 9)]: { tier: "ultra", durationDays: null },
  [_shift("QPI8OFE$=FLE;<I", 9)]: { tier: "ultra", durationDays: null },
  [_shift("QPI8OFE$I<C<8J<$)')-", 9)]: { tier: "ultra", durationDays: null },
}

export function validateSecretCode(code: string): { tier: SubscriptionTier; durationDays: number | null } | null {
  const normalized = code.trim().toUpperCase()
  const entry = SECRET_CODES[normalized]
  if (entry) return entry
  return null
}

// ═══════════════════════════════════════════════════════════════
// TOOL TIER MAP — MIRRORS packages/zyraxon/src/subscription/tier-map.ts
// This is the canonical runtime source of truth. UI gates and counts
// use the SAME assignment, so free users cannot unlock premium tools
// and vice versa.
// ═══════════════════════════════════════════════════════════════
export const TOOL_TIER_MAP: Record<string, SubscriptionTier> = {
  // FREE
  bash: "free", edit: "free", execute: "free", glob: "free",
  grep: "free", invalid: "free", list_mcp_resource_templates: "free", list_mcp_resources: "free",
  lsp: "free", memory: "free", patch: "free", plan: "free",
  question: "free", read: "free", read_mcp_resource: "free", skill: "free",
  todowrite: "free", webfetch: "free", websearch: "free", write: "free",
  x_analogy_add: "free", x_causal_add_link: "free", x_context_set: "free", x_doc_count_words: "free",
  x_doc_create: "free", x_doc_edit: "free", x_doc_markdown_to_html: "free", x_doc_read: "free",
  x_life_age: "free", x_life_aspect_ratio: "free", x_life_bmi: "free", x_life_calories: "free",
  x_life_color: "free", x_life_date_diff: "free", x_life_emi: "free", x_life_fuel: "free",
  x_life_gst: "free", x_life_heart_rate: "free", x_life_pace: "free", x_life_pixel_rem: "free",
  x_life_savings_goal: "free", x_life_temp: "free", x_life_text_stats: "free", x_life_tip: "free",
  x_life_unit: "free", x_life_wind_chill: "free", x_life_wpm: "free", x_math_combinatorics: "free",
  x_math_derivative: "free", x_math_geometry: "free", x_math_gradient: "free", x_math_integral: "free",
  x_math_matrix: "free", x_math_prime: "free", x_math_stats: "free", x_memory_append: "free",
  x_memory_create: "free", x_memory_delete: "free", x_memory_read: "free", x_memory_search: "free",
  x_memory_update: "free", x_memory_view: "free", x_reason_add_fact: "free", x_skill_create: "free",
  x_skill_delete: "free", x_skill_list: "free", x_spatial_add_obj: "free", x_subscription_status: "free",
  x_mode_switch: "free",
  x_task_create: "free", x_task_delete: "free", x_task_list: "free", x_task_run_now: "free",
  x_task_scheduler_status: "free", x_task_start_scheduler: "free", x_task_toggle: "free", x_world_add_object: "free",
  task: "free", system_info: "free",

  // MCP TOOL FALLBACKS — always free (the 4 MCP servers' tools)
  mcp_websearch: "free",
  nuphus_screenshot: "free", nuphus_list_windows: "free", nuphus_focus_window: "free", nuphus_click: "free",
  nuphus_type: "free", nuphus_hotkey: "free", nuphus_scroll: "free", nuphus_mouse_move: "free",
  nuphus_drag: "free", nuphus_ocr: "free", nuphus_clipboard_get: "free", nuphus_clipboard_set: "free",
  nuphus_browser_navigate: "free", nuphus_browser_snapshot: "free", nuphus_browser_click: "free", nuphus_browser_type: "free",
  nuphus_browser_screenshot: "free", nuphus_browser_cookies: "free", nuphus_browser_execute: "free",
  tp_apps: "free", tp_windows: "free", tp_elements: "free", tp_find: "free",
  tp_snapshot: "free", tp_get_element: "free", tp_element_at: "free", tp_diagnostics: "free",
  tp_activate_window: "free", tp_minimize_window: "free", tp_fullscreen_window: "free", tp_close_window: "free",
  tp_move_window: "free", tp_resize_window: "free", tp_find_window: "free", tp_monitor_count: "free",
  tp_click: "free", tp_double_click: "free", tp_right_click: "free", tp_click_at: "free",
  tp_double_click_at: "free", tp_right_click_at: "free", tp_mouse_move: "free", tp_drag: "free",
  tp_type_text: "free", tp_press_key: "free", tp_hotkey: "free", tp_scroll: "free",
  tp_set_value: "free", tp_set_numeric_value: "free", tp_focus: "free", tp_select_text: "free",
  tp_select_text_range: "free", tp_action: "free", tp_read_text: "free", tp_screenshot: "free",
  tp_screenshot_window: "free", tp_chrome_profiles: "free", tp_open_chrome_profile: "free", tp_new_tab: "free",
  tp_list_tabs: "free", tp_switch_tab: "free", tp_close_tab: "free", tp_wait_for: "free",
  tp_wait_for_app: "free", tp_wait_for_window: "free", tp_configure: "free",

  // PRO
  x_access_log: "pro", x_acid_ph_strong: "pro", x_acid_ph_weak: "pro", x_acid_titration: "pro",
  x_alert_create: "pro", x_anomaly_add: "pro", x_anomaly_alert_add: "pro", x_arduino_analog_read: "pro",
  x_arduino_connect: "pro", x_arduino_digital_write: "pro", x_astro_angular_sep: "pro", x_astro_escape_vel: "pro",
  x_astro_gravity: "pro", x_astro_habitable_zone: "pro", x_astro_julian_date: "pro", x_astro_luminosity: "pro",
  x_astro_orbital_period: "pro", x_astro_parallax: "pro", x_astro_redshift: "pro", x_astro_sidereal_time: "pro",
  x_audit_record: "pro", x_auth_add_client: "pro", x_auth_add_user: "pro", x_bias_add_dataset: "pro",
  x_bio_dna_rna: "pro", x_bio_gc_content: "pro", x_bio_hardy_weinberg: "pro", x_bio_hill_equation: "pro",
  x_bio_michaelis_menten: "pro", x_bio_population: "pro", x_bio_punnett: "pro", x_bio_shannon_index: "pro",
  x_bio_simpson_index: "pro", x_bt_scan: "pro", x_camera_connect: "pro", x_can_connect: "pro",
  x_can_send: "pro", x_captcha_click: "pro", x_captcha_detect: "pro", x_captcha_input: "pro",
  x_captcha_solve_image: "pro", x_causal_add_var: "pro", x_cert_generate: "pro", x_chain_adjust_diff: "pro",
  x_chain_block_reward: "pro", x_chain_difficulty: "pro", x_chain_gas: "pro", x_chain_impermanent_loss: "pro",
  x_chain_merkle: "pro", x_chain_nonce: "pro", x_chain_sha256: "pro", x_chain_staking: "pro",
  x_chain_tx_fee: "pro", x_chart_create: "pro", x_chem_buffer: "pro", x_chem_dilution: "pro",
  x_chem_electrochemistry: "pro", x_chem_gas_laws: "pro", x_chem_halflife: "pro", x_chem_limiting_reagent: "pro",
  x_chem_molar_mass: "pro", x_chem_moles: "pro", x_chem_nernst: "pro", x_chem_percent_composition: "pro",
  x_classify_add: "pro", x_cmd_register: "pro", x_dash_create_panel: "pro", x_db_bloat: "pro",
  x_db_buffer_pool: "pro", x_db_complexity: "pro", x_db_exec_time: "pro", x_db_pool_size: "pro",
  x_db_replication: "pro", x_db_selectivity: "pro", x_db_sharding: "pro", x_db_throughput: "pro",
  x_db_vacuum: "pro", x_decision_add_option: "pro", x_design_create_project: "pro", x_devops_availability: "pro",
  x_devops_container_eff: "pro", x_devops_deploy_rate: "pro", x_devops_error_rate: "pro", x_devops_infra_cost: "pro",
  x_devops_mtbf: "pro", x_devops_mttr: "pro", x_devops_pipeline: "pro", x_devops_scaling: "pro",
  x_devops_sla: "pro", x_ds_confusion_matrix: "pro", x_ds_cosine: "pro", x_ds_distance: "pro",
  x_ds_entropy: "pro", x_ds_gini: "pro", x_ds_gradient_descent: "pro", x_ds_kmeans: "pro",
  x_ds_monte_carlo: "pro", x_ds_multi_regression: "pro", x_ds_normalize: "pro", x_ds_sigmoid: "pro",
  x_ds_softmax: "pro", x_ds_standardize: "pro", x_ds_tfidf: "pro", x_eng_battery: "pro",
  x_eng_beam: "pro", x_eng_buckling: "pro", x_eng_concrete_mix: "pro", x_eng_filter_design: "pro",
  x_eng_flow_rate: "pro", x_eng_gear: "pro", x_eng_heat_exchanger: "pro", x_eng_impedance: "pro",
  x_eng_mohrs_circle: "pro", x_eng_motor: "pro", x_eng_pipe_flow: "pro", x_eng_power_factor: "pro",
  x_eng_resonance: "pro", x_eng_reynolds: "pro", x_eng_stress: "pro", x_eng_thermal_stress: "pro",
  x_eng_three_phase: "pro", x_eng_torsion: "pro", x_eng_transformer: "pro", x_eng_vibration: "pro",
  x_escalation_create: "pro", x_ethics_add_principle: "pro", x_event_log: "pro", x_export_csv: "pro",
  x_failure_add: "pro", x_fairness_add_model: "pro", x_fin_annuity: "pro", x_fin_beta: "pro",
  x_fin_black_scholes: "pro", x_fin_bond: "pro", x_fin_compound: "pro", x_fin_dividend_discount: "pro",
  x_fin_irr: "pro", x_fin_mortgage: "pro", x_fin_npv: "pro", x_fin_present_value: "pro",
  x_fin_roi: "pro", x_fin_sharpe: "pro", x_fin_stock: "pro", x_game_armor_reduction: "pro",
  x_game_cooldown: "pro", x_game_dps: "pro", x_game_expected_dmg: "pro", x_game_expected_loot: "pro",
  x_game_loot_chance: "pro", x_game_move_speed: "pro", x_game_total_xp: "pro", x_game_ttk: "pro",
  x_game_xp_for_level: "pro", x_geo_bearing: "pro", x_geo_erosion: "pro", x_geo_geothermal: "pro",
  x_geo_mohs: "pro", x_geo_permeability: "pro", x_geo_plate_velocity: "pro", x_geo_porosity: "pro",
  x_geo_radiometric: "pro", x_geo_rock_type: "pro", x_geo_seismic_density: "pro", x_gps_connect: "pro",
  x_heartbeat_start: "pro", x_i2c_read: "pro", x_idea_add_concept: "pro", x_imu_connect: "pro",
  x_imu_get_accel: "pro", x_innovation_add_tech: "pro", x_lidar_connect: "pro", x_lidar_get_pointcloud: "pro",
  x_ling_edit_distance: "pro", x_ling_entropy: "pro", x_ling_flesch: "pro", x_ling_morphemes: "pro",
  x_ling_ngrams: "pro", x_ling_pos: "pro", x_ling_syllables: "pro", x_ling_tfidf_sim: "pro",
  x_ling_ttr: "pro", x_ling_zipf: "pro", x_lora_connect: "pro", x_maint_add_task: "pro",
  x_mat_brinell: "pro", x_mat_bulk: "pro", x_mat_composite: "pro", x_mat_creep: "pro",
  x_mat_fatigue: "pro", x_mat_fracture: "pro", x_mat_shear: "pro", x_mat_thermal_expansion: "pro",
  x_mat_thermal_stress: "pro", x_mat_youngs: "pro", x_meteo_cloud_base: "pro", x_meteo_dew_point: "pro",
  x_meteo_heat_index: "pro", x_meteo_mixing_ratio: "pro", x_meteo_pet: "pro", x_meteo_pressure_alt: "pro",
  x_meteo_stability: "pro", x_meteo_virtual_temp: "pro", x_meteo_visibility: "pro", x_meteo_wind_chill: "pro",
  x_music_beat_freq: "pro", x_music_chord: "pro", x_music_doppler: "pro", x_music_duration_bpm: "pro",
  x_music_freq_note: "pro", x_music_interval: "pro", x_music_note_freq: "pro", x_music_scale: "pro",
  x_music_tempo_ms: "pro", x_music_tuning_table: "pro", x_net_bdp: "pro", x_net_broadcast: "pro",
  x_net_cidr_mask: "pro", x_net_int_ip: "pro", x_net_ip_int: "pro", x_net_jitter: "pro",
  x_net_mask_cidr: "pro", x_net_network_addr: "pro", x_net_tcp_throughput: "pro", x_net_usable_hosts: "pro",
  x_nlp_analyze: "pro", x_notify_add_channel: "pro", x_ocean_chlorophyll: "pro", x_ocean_coriolis: "pro",
  x_ocean_density: "pro", x_ocean_ekman: "pro", x_ocean_mixed_layer: "pro", x_ocean_rossby: "pro",
  x_ocean_sound_speed: "pro", x_ocean_tidal: "pro", x_ocean_wave_period: "pro", x_ocean_wave_speed: "pro",
  x_oil_add: "pro", x_pattern_add: "pro", x_physics_add_body: "pro", x_physics_em: "pro",
  x_physics_mechanics: "pro", x_physics_relativity: "pro", x_physics_thermo: "pro", x_physics_waves: "pro",
  x_policy_add: "pro", x_predict_add: "pro", x_radar_connect: "pro", x_rbac_add_role: "pro",
  x_relax_add_problem: "pro", x_remote_connect: "pro", x_rest_add_route: "pro", x_risk_add: "pro",
  x_rl_create_state: "pro", x_robot_dynamics: "pro", x_robot_fwd_kinematics: "pro", x_robot_heuristic: "pro",
  x_robot_inv_kinematics: "pro", x_robot_jacobian: "pro", x_robot_manipulability: "pro", x_robot_pid: "pro",
  x_robot_pose_error: "pro", x_robot_sensor_fusion: "pro", x_robot_workspace: "pro", x_rpi_connect: "pro",
  x_rpi_gpio_read: "pro", x_safety_validate: "pro", x_scenario_analyze: "pro", x_scenario_create: "pro",
  x_sdr_connect: "pro", x_sdr_get_fft: "pro", x_signal_analyze: "pro", x_sim_add_task: "pro",
  x_spare_add: "pro", x_status_add: "pro", x_storage_allocate: "pro", x_stream_create: "pro",
  x_sync_add_source: "pro", x_thermal_connect: "pro", x_thermal_trend_add: "pro", x_token_create: "pro",
  x_tradeoff_add: "pro", x_transparency_add: "pro", x_tree_create: "pro", x_tsdb_create: "pro",
  x_twin_create: "pro", x_uce_context: "pro", x_uce_devices: "pro", x_uce_history: "pro",
  x_uce_process: "pro", x_uce_register_device: "pro", x_ultrasonic_connect: "pro", x_vibration_add: "pro",
  x_vision_detect: "pro", x_widget_create: "pro", x_wifi_scan: "pro", x_ws_start: "pro",
  api_tester: "pro", apply_patch: "pro", code_analyzer: "pro", code_mode: "pro",
  media_fetch: "pro", screen_vision: "pro", self_evolve: "pro", svg_generate: "pro",
  x_behavior_rules: "pro", x_learn_from_task: "pro", x_media_data_extract: "pro", x_media_image_edit: "pro",
  x_media_ocr: "pro", x_media_video_process: "pro", x_plan_create: "pro", x_plan_execute: "pro",
  x_plan_status: "pro",

  // MAX
  x_access_check: "max", x_access_grant: "max", x_access_revoke: "max", x_anchor_calculate_scope: "max",
  x_anchor_drop: "max", x_anchor_retrieve: "max", x_atc_connect: "max", x_atc_declare_emergency: "max",
  x_atc_disconnect: "max", x_atc_read_back: "max", x_atc_request_clearance: "max", x_atc_set_squawk: "max",
  x_atc_tune: "max", x_auto_detect_power_loss: "max", x_auto_initiate: "max", x_auto_maintain: "max",
  x_ballast_add_tank: "max", x_ballast_fill: "max", x_ballast_get_stability: "max", x_breaker_add: "max",
  x_bulldozer_get_grade: "max", x_bulldozer_push: "max", x_bulldozer_set_blade: "max", x_cabin_detect_decompression: "max",
  x_cabin_set_altitude: "max", x_cnc_get_status: "max", x_cnc_load_program: "max", x_cnc_start: "max",
  x_cnc_stop: "max", x_collision_calc_ttc: "max", x_collision_should_brake: "max", x_collision_should_evade: "max",
  x_concrete_get_consistency: "max", x_concrete_set_ratio: "max", x_concrete_start_mix: "max", x_constellation_add_sat: "max",
  x_constellation_coverage: "max", x_constellation_revisit: "max", x_construction_drone_capture: "max", x_construction_drone_get_model: "max",
  x_construction_drone_set_site: "max", x_conveyor_start: "max", x_conveyor_stop: "max", x_crane_check_wind: "max",
  x_crane_set_boom: "max", x_crane_set_trolley: "max", x_crop_add_field: "max", x_crop_predict_yield: "max",
  x_crop_update_growth: "max", x_ct_agents: "max", x_ct_collab: "max", x_ct_register: "max",
  x_ct_transfer: "max", x_cyber_block_ip: "max", x_cyber_detect_brute_force: "max", x_cyber_detect_port_scan: "max",
  x_decrypt_data: "max", x_delivery_assign: "max", x_delivery_create: "max", x_delivery_track: "max",
  x_deorbit_calc_burn: "max", x_deorbit_get_window: "max", x_dms_get_alertness: "max", x_dms_get_fatigue: "max",
  x_dms_update: "max", x_drug_add_medication: "max", x_drug_check_interactions: "max", x_drug_get_contraindications: "max",
  x_ea_adapt: "max", x_ea_analyze: "max", x_ea_mood: "max", x_eclipse_power_budget: "max",
  x_eclipse_predict: "max", x_emergency_activate: "max", x_encrypt_data: "max", x_encrypt_hash: "max",
  x_engine_add: "max", x_engine_check_health: "max", x_excavator_dig: "max", x_excavator_set_arm: "max",
  x_excavator_set_bucket: "max", x_failsafe_add_rule: "max", x_fire_activate: "max", x_fire_detect_heat: "max",
  x_fire_detect_smoke: "max", x_fmea_add: "max", x_geofence_add_zone: "max", x_geofence_check: "max",
  x_geofence_violations: "max", x_ground_station_add: "max", x_ground_station_next_pass: "max", x_ground_station_schedule: "max",
  x_harvest_get_optimal_date: "max", x_harvest_plan_schedule: "max", x_harvest_set_field: "max", x_heli_weather_get_correction: "max",
  x_heli_weather_get_crosswind: "max", x_hover_correction: "max", x_hover_get_error: "max", x_hover_set_target: "max",
  x_hull_add_sensor: "max", x_hull_check_integrity: "max", x_hull_detect_leak: "max", x_hvac_get_efficiency: "max",
  x_hvac_set_humidity: "max", x_hvac_set_temp: "max", x_interlock_add: "max", x_intrusion_arm: "max",
  x_intrusion_check_breach: "max", x_intrusion_set_zone: "max", x_irrigation_get_usage: "max", x_irrigation_set_zone: "max",
  x_irrigation_start: "max", x_launch_calc_window: "max", x_launch_check_constraints: "max", x_launch_get_next: "max",
  x_lidar_add_point: "max", x_lidar_downsample: "max", x_lidar_get_volume: "max", x_load_attach: "max",
  x_load_compensate: "max", x_load_detach: "max", x_mapper_add_photo: "max", x_mapper_generate_model: "max",
  x_mapper_set_flight: "max", x_medical_check_alerts: "max", x_medical_get_vitals: "max", x_medical_update_vitals: "max",
  x_mp_connect: "max", x_mp_query: "max", x_mp_stats: "max", x_mp_store: "max",
  x_nav_chart_add_waypoint: "max", x_nav_chart_get_eta: "max", x_nav_chart_set_route: "max", x_notam_add: "max",
  x_notam_check_runway: "max", x_notam_get_by_location: "max", x_obstacle_add_3d: "max", x_obstacle_find_path: "max",
  x_obstacle_get_avoidance: "max", x_oc_create: "max", x_oc_projects: "max", x_oc_templates: "max",
  x_patient_get_alert_level: "max", x_patient_set: "max", x_patient_update_vitals: "max", x_payload_confirm: "max",
  x_payload_create: "max", x_payload_deploy: "max", x_pedestrian_add: "max", x_pedestrian_predict: "max",
  x_pedestrian_risk: "max", x_pest_add_observation: "max", x_pest_get_recommendation: "max", x_pest_get_risk: "max",
  x_pilot_release_override: "max", x_pilot_request_override: "max", x_plc_connect: "max", x_plc_read_register: "max",
  x_plc_write_register: "max", x_power_add_generator: "max", x_power_add_load: "max", x_power_get_balance: "max",
  x_quantum_bloch: "max", x_quantum_circuit_depth: "max", x_quantum_cnot: "max", x_quantum_concurrence: "max",
  x_quantum_decomposition: "max", x_quantum_entropy: "max", x_quantum_fidelity: "max", x_quantum_hadamard: "max",
  x_quantum_rx_gate: "max", x_rail_emergency_stop: "max", x_rail_set_signal: "max", x_rail_set_speed: "max",
  x_rb_control: "max", x_rb_register: "max", x_rb_scene_activate: "max", x_rb_scene_create: "max",
  x_rb_states: "max", x_redundancy_add: "max", x_road_detect_hazard: "max", x_road_get_recommendation: "max",
  x_road_update_friction: "max", x_robot_get_kinematics: "max", x_robot_move_linear: "max", x_robot_set_joint: "max",
  x_rotor_get_rpm: "max", x_rotor_health: "max", x_rotor_set_collective: "max", x_rotor_set_cyclic: "max",
  x_rotor_set_pedal: "max", x_rs_results: "max", x_rs_simulate: "max", x_rtk_get_accuracy: "max",
  x_rtk_get_fix: "max", x_rtk_set_position: "max", x_runway_calc_landing_distance: "max", x_runway_get_braking: "max",
  x_runway_set_condition: "max", x_sar_plan_grid: "max", x_sar_plan_spiral: "max", x_sar_set_area: "max",
  x_scada_add_sensor: "max", x_scada_check_limits: "max", x_scada_update_value: "max", x_se_analyze: "max",
  x_se_suggest: "max", x_se_trend: "max", x_sec_caesar: "max", x_sec_cve: "max",
  x_sec_entropy: "max", x_sec_firewall: "max", x_sec_hash_id: "max", x_sec_malware_sig: "max",
  x_sec_password: "max", x_sec_port_scan: "max", x_sec_ssl: "max", x_sec_subnet: "max",
  x_sec_xor: "max", x_seismic_add_sensor: "max", x_seismic_detect_pwave: "max", x_seismic_get_magnitude: "max",
  x_soil_add_sample: "max", x_soil_get_heatmap: "max", x_soil_get_recommendation: "max", x_sonar_add_target: "max",
  x_sonar_classify: "max", x_sonar_get_targets: "max", x_spray_get_coverage: "max", x_spray_plan_swath: "max",
  x_spray_set_field: "max", x_stage_deploy_chutes: "max", x_stage_separate: "max", x_stage_touchdown: "max",
  x_surveillance_add_camera: "max", x_surveillance_detect_motion: "max", x_surveillance_set_recording: "max", x_swarm_add_drone: "max",
  x_swarm_consensus: "max", x_swarm_leader_election: "max", x_tcas_calculate_resolution: "max", x_tcas_detect_traffic: "max",
  x_thermal_check_limits: "max", x_thermal_monitor: "max", x_thermal_predict_flux: "max", x_tm_bugs: "max",
  x_tm_evolution: "max", x_tm_predict: "max", x_tm_snapshot: "max", x_tm_timeline: "max",
  x_total_station_measure_angle: "max", x_total_station_measure_distance: "max", x_traffic_recommended_speed: "max", x_traffic_set_signal: "max",
  x_traffic_should_proceed: "max", x_v2x_connect: "max", x_v2x_send_v2i: "max", x_v2x_send_v2v: "max",
  x_veh_boat_connect: "max", x_veh_boat_emergency: "max", x_veh_boat_heading: "max", x_veh_boat_navigate: "max",
  x_veh_boat_throttle: "max", x_veh_car_clear_dtcs: "max", x_veh_car_climate: "max", x_veh_car_connect: "max",
  x_veh_car_dtcs: "max", x_veh_car_fuel: "max", x_veh_car_horn: "max", x_veh_car_lights: "max",
  x_veh_car_lock: "max", x_veh_car_rpm: "max", x_veh_car_speed: "max", x_veh_car_start: "max",
  x_veh_car_stop: "max", x_veh_car_unlock: "max", x_veh_drone_arm: "max", x_veh_drone_attitude: "max",
  x_veh_drone_connect: "max", x_veh_drone_disarm: "max", x_veh_drone_emergency: "max", x_veh_drone_fly_to: "max",
  x_veh_drone_geofence: "max", x_veh_drone_land: "max", x_veh_drone_mode: "max", x_veh_drone_rtl: "max",
  x_veh_drone_speed: "max", x_veh_drone_takeoff: "max", x_veh_drone_waypoints: "max", x_veh_fleet_create_car: "max",
  x_veh_fleet_create_drone: "max", x_veh_fleet_disconnect: "max", x_veh_fleet_emergency_stop: "max", x_veh_fleet_telemetry: "max",
  x_vtol_energy: "max", x_vtol_plan_landing: "max", x_vtol_plan_takeoff: "max", x_watchdog_start: "max",
  x_water_get_quality: "max", x_water_set_flow: "max", x_water_set_ph: "max", x_weather_check_icing: "max",
  x_weather_check_turbulence: "max", x_weather_get_winds_aloft: "max", x_weather_parse_metar: "max", x_wind_get_vector: "max",
  x_wind_update_gps: "max", x_wind_update_imu: "max",
  site_create: "max", site_publish: "max", site_unpublish: "max", site_domain: "max",
  site_preview: "max", github_connect: "max", external_directory: "max",
  x_cdp_connect: "max", x_cdp_disconnect: "max", x_comp_click_at: "max", x_comp_drag: "max",
  x_comp_key_press: "max", x_comp_list_windows: "max", x_comp_move_mouse: "max", x_comp_open_app: "max",
  x_comp_screenshot: "max", x_comp_scroll: "max", x_comp_type_text: "max",

  // ULTRA
  omni_backgroundLoop: "ultra", omni_behaviorCascade: "ultra", omni_costRouter: "ultra", omni_gitPair: "ultra",
  omni_ideaToDeploy: "ultra", omni_knowledgeGraph: "ultra", omni_liveObservability: "ultra", omni_multiFileCompose: "ultra",
  omni_sandboxRuntime: "ultra", omni_securityScan: "ultra", omni_selfEvolvingPrompt: "ultra", omni_silentPrecompile: "ultra",
  omni_terminalAutonomy: "ultra", omni_visualContextSync: "ultra", omni_zeroTrustStrip: "ultra", ultra_autodeploy: "ultra",
  ultra_code_review: "ultra", ultra_codegen: "ultra", ultra_performance: "ultra", ultra_quantum: "ultra",
  ultra_refactor: "ultra", ultra_security_sweep: "ultra", ultra_test_gen: "ultra", ultra_ultraAutoDeploy: "ultra",
  ultra_ultraCodeGen: "ultra", ultra_ultraDebug: "ultra", ultra_ultraDocGen: "ultra", ultra_ultraPerformance: "ultra",
  ultra_ultraRefactor: "ultra", ultra_ultraSecuritySweep: "ultra", ultra_ultraTestGen: "ultra", x_guardian_clear: "ultra",
  x_guardian_context: "ultra", x_guardian_scan: "ultra", x_guardian_status: "ultra", x_quantum_shor_period: "ultra",
  x_singularity_evolution: "ultra", x_singularity_heal: "ultra", x_singularity_learn: "ultra", x_singularity_process: "ultra",
  x_singularity_state: "ultra", x_veh_fleet_create_rocket: "ultra", x_veh_rocket_abort: "ultra", x_veh_rocket_connect: "ultra",
  x_veh_rocket_countdown: "ultra", x_veh_rocket_engine: "ultra", x_veh_rocket_fairing: "ultra", x_veh_rocket_launch: "ultra",
  x_veh_rocket_payload: "ultra", x_veh_rocket_stage: "ultra", x_veh_rocket_throttle: "ultra", x_veh_rocket_trajectory: "ultra",
  x_veh_sat_antenna: "ultra", x_veh_sat_attitude: "ultra", x_veh_sat_camera: "ultra", x_veh_sat_connect: "ultra",
  x_veh_sat_deorbit: "ultra", x_veh_sat_orbit: "ultra", x_veh_sat_safemode: "ultra", x_veh_sat_solar: "ultra",
  x_veh_sat_thruster: "ultra",
}

export function getToolRequiredTier(toolId: string): SubscriptionTier {
  return TOOL_TIER_MAP[toolId] ?? "max"
}

export const SUBSCRIPTION_PLANS: Record<SubscriptionTier, SubscriptionPlan> = {
  free: {
    id: "free",
    name: "Free",
    price: 0,
    currency: "USD",
    durationDays: null,
    description: "Get started with the basics",
    features: [
      "Basic AI Chat",
      "File System Access (Read/Write/Edit)",
      "Shell Execution (Bash/PowerShell)",
      "Web Search & Fetch",
      "Glob & Grep File Search",
      "Todo Task Management",
      "Basic Memory (100 entries)",
      "Math & Science Tools",
      "Daily Life Tools",
      "Document & Skill Tools",
      "Basic Browser Automation",
      "Mode Switching (general/build/plan/explore/vision)",
    ],
    toolCount: 126,
    memoryOptimization: "Basic (100 entries, 10MB cache)",
    maxAgents: 1,
    maxProjects: "3",
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 5,
    currency: "USD",
    durationDays: 15,
    description: "More power for professionals",
    features: [
      "Everything in Free",
      "Unlimited Projects",
      "Memory & Context Sync (500 entries)",
      "Code Analysis & Planning",
      "Self-Evolution & Screen Vision",
      "API Testing Tools",
      "Aviation Systems",
      "Ground Vehicle Systems",
      "Drone Systems",
      "Helicopter Systems",
      "ML & Safety Tools",
      "Common Sense & Ethics AI",
      "Creativity Engine",
      "Multi-Agent (up to 3 agents)",
      "Priority Processing",
    ],
    toolCount: 304,
    memoryOptimization: "Pro (500 entries, 50MB cache)",
    maxAgents: 3,
    maxProjects: "Unlimited",
  },
  max: {
    id: "max",
    name: "Max",
    price: 15,
    currency: "USD",
    durationDays: 60,
    description: "Built for teams and scale",
    features: [
      "Everything in Pro",
      "Space Systems",
      "Industrial Control",
      "Infrastructure Systems",
      "Security & Surveillance",
      "Survey & Mapping",
      "Agriculture Systems",
      "Marine Systems",
      "Construction Systems",
      "Physical Interface & Sensors",
      "SDR & Radio",
      "Digital Twin & Simulation",
      "Dashboard & Visualization",
      "Alert & Notification",
      "Data Logging & Export",
      "Remote Control",
      "Predictive Maintenance",
      "Decision Support",
      "Authorization & Auth",
      "Multi-Agent (up to 8 agents)",
      "Team Workspace (3 members)",
      "GitHub Integration",
    ],
    toolCount: 337,
    memoryOptimization: "Max (2000 entries, 200MB cache)",
    maxAgents: 8,
    maxProjects: "Unlimited + Team",
  },
  ultra: {
    id: "ultra",
    name: "Ultra",
    price: 99,
    currency: "USD",
    durationDays: 365,
    description: "Maximum power. No limits.",
    features: [
      "Everything in Max",
      "Singularity AI Engine",
      "Guardian System",
      "OMNI-KERNEL 15-layer system",
      "Ultra Code Generator",
      "Ultra Security Sweeper",
      "Ultra Performance Optimizer",
      "Ultra Refactoring Engine",
      "Ultra Test Generator",
      "Ultra Auto-Deploy Pipeline",
      "Ultra Code Reviewer",
      "Ultra Quantum Analyzer",
      "Unlimited Agents (no cap)",
      "Full Cloud Execution (24/7)",
      "Team Workspace (10 members)",
      "Custom Models & Settings",
      "Priority Support",
      "Early Access to New Features",
      "Memory (10000 entries, 1GB cache)",
    ],
    toolCount: 38,
    memoryOptimization: "Ultra (10000 entries, 1GB cache)",
    maxAgents: -1,
    maxProjects: "Unlimited + Team + Enterprise",
  },
}

export const TIER_STATS: Record<SubscriptionTier, { totalTools: number; categories: string[] }> = {
  free: {
    totalTools: 126,
    categories: ["Core AI", "Math", "Science", "Finance", "Data Science", "Security Basics", "Daily Life", "Memory", "Documents", "Tasks", "Captcha", "Subscription", "Acid/Base", "Chemistry", "Biology", "Life Tools", "System Info", "Web Search", "Nuphus Desktop", "Touchpoint Desktop"],
  },
  pro: {
    totalTools: 304,
    categories: ["Everything in Free", "Aviation", "Ground Vehicles", "Drones", "Helicopters", "ML & Safety", "Common Sense & Ethics", "Creativity", "Data Science Advanced", "Finance Advanced", "Vehicle Systems", "Planning", "Media Processing", "OCR", "Code Analysis", "API Testing", "Screen Vision", "Self-Evolution", "Task Automation"],
  },
  max: {
    totalTools: 337,
    categories: ["Everything in Pro", "Space", "Industrial", "Infrastructure", "Security", "Survey", "Agriculture", "Marine", "Construction", "Physical Interface", "SDR", "Digital Twin", "Dashboard", "Alert", "Data Logger", "Remote Control", "Predictive Maintenance", "Decision Support", "Authorization", "Extended AI", "Engineering", "Advanced Security", "CDP Browser", "Computer Control", "Site Builder"],
  },
  ultra: {
    totalTools: 38,
    categories: ["Everything in Max", "Singularity", "Guardian", "Universal Command Engine", "Ultra Tools", "Self-Improvement"],
  },
}