// Copyright (c) 2026 onelpawarai. All rights reserved.

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

/// <reference path="../sst-env.d.ts" />

import "sst"
export {}