#!/usr/bin/env bun
// SPDX-License-Identifier: LicenseRef-ZYRAXON-ZSL-X
// Copyright (c) 2026 onelpawarai. All rights reserved.

/**
 * Full local-to-GitHub sync in one commit.
 *
 * The earlier chunked run was slow because every path was staged through its
 * own pathspec batch, and git rebuilds the index each time. This does the same
 * work with two git calls: `git add -A` for the whole tree, then a single
 * `git rm --cached` for the build output that must leave the remote.
 */

import { gitAsync, gitPathspec } from "./sync-plan"
import { isBuildOutput } from "./sync-paths"

const BASE = process.env.SYNC_BASE ?? "origin/main"
const BRANCH = process.env.SYNC_BRANCH ?? "zyraxon/full-sync"
const PUSH = process.argv.includes("--push")
const MERGE = process.argv.includes("--merge")

// Root the branch at the base commit. The remote history was rewritten at some
// point, so the previous local tip shares no ancestry with origin/main and
// GitHub refuses to open a pull request from it.
const base = await gitAsync(["rev-parse", BASE])
await gitAsync(["symbolic-ref", "HEAD", `refs/heads/${BRANCH}`])
await gitAsync(["update-ref", `refs/heads/${BRANCH}`, base])
await gitAsync(["read-tree", BASE])

console.log(`base     ${BASE}`)
console.log(`branch   ${BRANCH}`)

console.log("git add -A")
const addStart = Date.now()
await gitAsync(["add", "-A"])
console.log(`  staged in ${Math.round((Date.now() - addStart) / 1000)}s`)

// `git add -A` also picked the regenerated build output back up, because git
// only applies the ignore rules to untracked paths. Drop it from the index so it
// leaves the remote while staying on disk.
const staged = (await gitAsync(["diff", "--cached", "--name-only", "-z"], true)).split("\0").filter(Boolean)
const buildOutput = staged.filter(isBuildOutput)
const otherStaged = staged.filter((path) => !isBuildOutput(path))
console.log(`staged   ${staged.length} (${otherStaged.length} project, ${buildOutput.length} build output)`)

if (buildOutput.length) {
  console.log(`git rm --cached ${buildOutput.length} build output paths`)
  await gitPathspec(["rm", "-r", "-q", "--cached", "--ignore-unmatch"], buildOutput)
}

const final = (await gitAsync(["diff", "--cached", "--name-only", "-z"], true)).split("\0").filter(Boolean)
const systems = [...new Set(final.map(systemOf))].sort()
console.log(`final    ${final.length} paths in ${systems.length} systems`)

const message = [
  `feat(zyraxon): sync the full local project tree`,
  ``,
  `Brings the whole working tree in line with the remote in a single pass.`,
  ``,
  `- tracked paths in this commit: ${final.length}`,
  `- build output left untracked: ${buildOutput.length} (\`dist\`, \`out\` are regenerated by the build)`,
  `- systems: ${systems.length}`,
  ``,
  ...systems.map((system) => `  - ${system}`),
  ``,
  `The prebuilt packages vendored under \`packages/desktop/resources\` are tracked,`,
  `because the application ships them.`,
].join("\n")

await gitAsync(["commit", "-q", "--no-verify", "-m", message])
console.log(`commit   ${(await gitAsync(["rev-parse", "--short", "HEAD"]))}`)

if (!PUSH) {
  console.log("\n--push not given, stopping before network")
  process.exit(0)
}

console.log("\npushing")
const pushStart = Date.now()
await gitAsync(["push", "--no-verify", "--force", "origin", `${BRANCH}:${BRANCH}`])
console.log(`pushed in ${Math.round((Date.now() - pushStart) / 1000)}s`)

if (!MERGE) process.exit(0)

console.log("\nopening pull request")
const create = Bun.spawn(
  ["gh", "pr", "create", "--base", "main", "--head", BRANCH, "--title", message.split("\n")[0], "--body", message],
  { stdout: "pipe", stderr: "pipe" },
)
const createOut = (await new Response(create.stdout).text()) + (await new Response(create.stderr).text())
console.log(createOut.trim().split("\n").filter(Boolean).slice(-1)[0] ?? createOut.trim())

console.log("\nmerging")
const merge = Bun.spawn(["gh", "pr", "merge", BRANCH, "--merge", "--delete-branch=false"], {
  stdout: "pipe",
  stderr: "pipe",
})
const mergeOut = (await new Response(merge.stdout).text()).trim()
const mergeErr = (await new Response(merge.stderr).text()).trim()
console.log(mergeOut || mergeErr)
console.log(`merge exit ${await merge.exited}`)

await gitAsync(["fetch", "origin", "--prune"], true)
console.log(`origin/main is now ${await gitAsync(["rev-parse", "--short", "origin/main"])}`)

function systemOf(path: string): string {
  const parts = path.split("/")
  if (parts[0] === "packages" && parts[1]) {
    const area = parts.slice(2).find((part) => part && !["src", "test", "script", "resources"].includes(part))
    return `packages/${parts[1]}${area ? `/${area}` : ""}`
  }
  return parts.slice(0, 2).join("/") || path
}
