// Copyright (c) 2026 onelpawarai. All rights reserved.

/**
 * Shared path rules for the full sync.
 *
 * The repository vendors a lot of prebuilt code under the desktop app's
 * `resources` tree, and many of those packages ship their own `dist` folders.
 * Only this project's own build output is regenerated by the build, so only
 * that may be excluded: a `dist`/`out` segment counts as build output unless
 * it sits under a vendored `resources` path.
 */
export const isBuildOutput = (path: string) => {
  if (path.includes("/resources/")) return false
  return /(^|\/)(dist|out|dist-ssr)(\/|$)/.test(path)
}
