// SPDX-License-Identifier: LicenseRef-ZYRAXON-ZSL-X
// Copyright (c) 2026 onelpawarai. All rights reserved.

// This file is generated by icon spritesheet generator

export const iconNames = [
  "vscode",
  "cursor",
  "zed",
  "file-explorer",
  "finder",
  "terminal",
  "iterm2",
  "ghostty",
  "warp",
  "xcode",
  "android-studio",
  "antigravity",
  "textmate",
  "powershell",
  "sublime-text",
] as const

export type IconName = (typeof iconNames)[number]
